# Generated by Django 3.2.12 on 2022-08-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('internship_link', models.CharField(max_length=150)),
                ('Video_link_1', models.CharField(max_length=200, null=True)),
                ('Video_link_2', models.CharField(max_length=200, null=True)),
                ('Video_link_3', models.CharField(max_length=200, null=True)),
                ('Video_link_4', models.CharField(max_length=200, null=True)),
                ('Video_link_5', models.CharField(max_length=200, null=True)),
                ('Video_link_6', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
