# Generated by Django 3.2.12 on 2022-08-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_info_video_link_7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Video_link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Video_link_1', models.CharField(max_length=200, null=True)),
                ('Video_link_2', models.CharField(max_length=200, null=True)),
                ('Video_link_3', models.CharField(max_length=200, null=True)),
                ('Video_link_4', models.CharField(max_length=200, null=True)),
                ('Video_link_5', models.CharField(max_length=200, null=True)),
                ('Video_link_6', models.CharField(max_length=200, null=True)),
                ('Video_link_7', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='Video_link_1',
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='Video_link_2',
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='Video_link_3',
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='Video_link_4',
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='Video_link_5',
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='Video_link_6',
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='Video_link_7',
        ),
    ]
