# Generated by Django 3.2.12 on 2022-08-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220818_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_video_link',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_info'),
        ),
    ]
