# Generated by Django 3.2.12 on 2022-08-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_video_link_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering_Video_Embed_Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_info')),
            ],
        ),
        migrations.DeleteModel(
            name='Company_Video_link',
        ),
    ]
