# Generated by Django 3.2.12 on 2022-08-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20220818_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others_Video_Embed_Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_info')),
            ],
        ),
        migrations.CreateModel(
            name='Finance_Video_Embed_Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_info')),
            ],
        ),
    ]
