# Generated by Django 3.2.12 on 2022-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_finance_video_embed_code_others_video_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='logo',
            field=models.ImageField(default='static/images/progamiz.jpg', null=True, upload_to='media/company/logo/'),
        ),
    ]
