# Generated by Django 3.2.12 on 2022-08-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_info_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Others_Video_Embed_Code',
            new_name='Marketing_Video_Embed_Code',
        ),
    ]
